create Database customer_behaviour;
Select * from customer_shopping
limit 5;

-- 1.what is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount ) as reevnue
from customer_shopping 
group by gender;

-- 2.Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer_shopping
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_shopping);

-- 3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating), 2) as "Average Product Rating"
from customer_shopping
group by item_purchased
order by avg(review_rating)desc
limit 5;

-- 4.Do subscribed customers spend more? Compare average spend and total revenue  between subscribers and non-subcribers.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount), 2) as avg_spend,
round(sum(purchase_amount), 2) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue, avg_spend desc;

-- 5. Which 5 product have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100 * sum(case when discount_applied ='yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;

-- 6.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case
when previous_purchases = 1 then'New'
when previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal'
End as customer_segment
from customer_shopping
)
select customer_segment, count(*) as "NUmber of Customers"
from customer_type
group by customer_segment;

-- 7.What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer_shopping
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 8. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status;

-- 9. what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping
group by age_group
order by total_revenue desc;








